---
# Splunk Global Vars

# Base Config
splunk:
  version: 8.2.6
  rpm_binary: splunk-8.2.6.rpm
  deb_binary: splunk-8.2.6.deb
  download_url: "http://192.168.33.1:8000/"
  checksum: md5:89e80e1822be6c02c9f6754215bfa1e8
  web:
    enableSplunkWebSSL: true
    httpport: 8000

# Web UI admin pw
admin_pw: darkhelmet

# Cluster Config
cluster:
  secret: SpaceWinnebago # secret key
  label:
    idx: idx_cluster # cluster label
    shc: sh_cluster
  replication_factor: 3 # 3 is default
  search_factor: 2 # 2 is default

