---
- hosts: all
  tasks:
    - name: include vars
      include_vars: "config.yaml"

- name: Deploy the cluster master indexer
  import_playbook: playbooks/01_master_IDX.yaml

- name: Deploy cluster slave indexers
  import_playbook: playbooks/02_cluster_IDX.yaml

- name: Deploy the search head deployers
  import_playbook: playbooks/03_deployer_SHC.yaml

- name: Deploy the search head cluster
  import_playbook: playbooks/04_cluster_SHC.yam

- name: Perform final clean up and config tasks
  import_playbook: playbooks/05_final.yaml

